In [2]:
import numpy as np 
a = np.matrix('2 3 1; -1 1 0; 1 2 -1')  
b = np.matrix('1 2 1; 0 1 2; 3 1 1')  
c = a.dot(b)  
print(c) 
d = b.dot(a)  
print(d) 
g = c - d 
print(g) 

[[ 5  8  9]
 [-1 -1  1]
 [-2  3  4]]
[[ 1  7  0]
 [ 1  5 -2]
 [ 6 12  2]]
[[ 4  1  9]
 [-2 -6  3]
 [-8 -9  2]]


In [3]:
import numpy as np 
a = np.array([[-1, 0, 2], [0, 1, 0], [1, 2, -1]]) 
power = np.linalg.matrix_power(a, 2) 
print(power) 

[[ 3  4 -4]
 [ 0  1  0]
 [-2  0  3]]


In [4]:
import numpy as np 
a = np.matrix('3 5; 6 -1') 
b = np.matrix('2 1; -3 2') 
c = a.dot(b) 
print(c) 
        
    

[[-9 13]
 [15  4]]


In [5]:
import numpy as np 
a = np.matrix('0 2 0; 3 4 5; 6 7 8') 
print(a) 
np.linalg.det(a) 

[[0 2 0]
 [3 4 5]
 [6 7 8]]


12.0

In [6]:
import numpy as np 
a = np.matrix('1 2 3 4; -2 1 -4 3; 3 -4 -1 2; 4 3 -2 -1') 
print(a) 
np.linalg.det(a) 

[[ 1  2  3  4]
 [-2  1 -4  3]
 [ 3 -4 -1  2]
 [ 4  3 -2 -1]]


900.0000000000009

In [7]:
import numpy as np 
a = np.matrix('1 2 2; 2 1 -2; 2 -2 1') 
a_inv = np.linalg.inv(a) 
print(a_inv) 

[[ 0.11111111  0.22222222  0.22222222]
 [ 0.22222222  0.11111111 -0.22222222]
 [ 0.22222222 -0.22222222  0.11111111]]


In [8]:
import numpy as np 
a = np.matrix('1 2 3 4; 3 -1 2 5; 1 2 3 4; 1 3 4 5') 
rank = np.linalg.matrix_rank(a) 
print(rank) 


2


In [9]:
import numpy as np 
a = np.matrix('2 -1 1; 3 2 2; 1 -2 1') 
b = np.matrix('2; -2; 1') 
print('A=', a) 
print('B=',b) 
a_inv = np.linalg.inv(a) 
print(a_inv) 
x = a_inv.dot(b) 
print('X=',x) 

A= [[ 2 -1  1]
 [ 3  2  2]
 [ 1 -2  1]]
B= [[ 2]
 [-2]
 [ 1]]
[[ 1.2 -0.2 -0.8]
 [-0.2  0.2 -0.2]
 [-1.6  0.6  1.4]]
X= [[ 2.]
 [-1.]
 [-3.]]


In [10]:
import numpy as np 
a = np.matrix('2 -1 1; 3 2 2; 1 -2 1') 
print('A=',a) 
b = np.matrix('2; -2; 1') 
print('B=',b) 

def kramer (a, b): 
    a_det = np.linalg.det(a) 
    print('Детермінант матриці = ', a_det) 

    if (a_det != 0): 
        print ('Розв*язуємо систему') 

        x_m = np.matrix(a) 
        x_m[:, 0] = b  
        print('x_m=', x_m) 
        y_m = np.matrix(a) 
        y_m[:, 1] = b  
        print('y_m=',y_m) 

        z_m = np.matrix(a) 
        z_m[:, 2] = b  
        print('z_m=',z_m) 

        x = np.linalg.det(x_m) / a_det 
        y = np.linalg.det(y_m) / a_det 
        z = np.linalg.det(z_m) / a_det 
        print('X = ', round(x,5)) 
        print('Y=', round(y,5)) 
        print('Z=', round(z,5)) 
    else: 
        print('Розв*язків немає') 
kramer(a,b) 

A= [[ 2 -1  1]
 [ 3  2  2]
 [ 1 -2  1]]
B= [[ 2]
 [-2]
 [ 1]]
Детермінант матриці =  5.000000000000001
Розв*язуємо систему
x_m= [[ 2 -1  1]
 [-2  2  2]
 [ 1 -2  1]]
y_m= [[ 2  2  1]
 [ 3 -2  2]
 [ 1  1  1]]
z_m= [[ 2 -1  2]
 [ 3  2 -2]
 [ 1 -2  1]]
X =  2.0
Y= -1.0
Z= -3.0


In [11]:
import numpy as np 
a = np.array([[0, 2, 1], [0, 1, 2], [1, 2, 3]]) 
print(a) 
suma = np.sum(a) 
print("Сума всіх елемнтів =", suma) 
suma1 = np.sum(a[0]) 
print("Сума елемнтів 1 рядка =",suma1) 
suma2 = np.sum(a[1]) 
print("Сума елементів 2 рядка =",suma2) 
suma3 = np.sum(a[2]) 
print("Сума елементів 3 рядка =",suma3) 
portion1 = suma1 / suma * 100 
portion2 = suma2 / suma * 100 
portion3 = suma3 / suma * 100 
print("Доля 1 рядка =", portion1,"%") 


[[0 2 1]
 [0 1 2]
 [1 2 3]]
Сума всіх елемнтів = 12
Сума елемнтів 1 рядка = 3
Сума елементів 2 рядка = 3
Сума елементів 3 рядка = 6
Доля 1 рядка = 25.0 %
